<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.1.0</Version>
        <AssemblyTitle>Example reactor plugin</AssemblyTitle>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Reactor.Empostor\Reactor.Empostor.csproj">
            <Private>false</Private>
        </ProjectReference>
    </ItemGroup>

</Project>
